server:
  port: 8888

spring:
  application:
    name: hrms-gateway

  cloud:
    gateway:
      # 精确匹配放前面，模糊匹配放后面
      routes:
        - id: hrms-system
          uri: lb://hrms-system
          predicates:
            - Path=/admin/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: hrms-enterprise
          uri: lb://hrms-enterprise
          predicates:
            - Path=/enterprise/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: third_part
          uri: lb://third-part
          predicates:
            - Path=/third-part/**


#        - id: admin_route
#          uri: lb://renren-fast
#          predicates:
#            - Path=/api/**
#          filters:
#            - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment}
